export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REGISTRATION_REQUESTED = 'REGISTRATION_REQUESTED'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED'


export const POST_MOVIE_REQUESTED = 'POST_MOVIE_REQUESTED';
export const POST_MOVIE_SUCCESS = 'POST_MOVIE_SUCCESS';
export const POST_MOVIE_FAILED = 'POST_MOVIE_FAILED';


export const GET_MOVIE_REQUESTED = 'GET_MOVIE_REQUESTED';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAILED = 'GET_MOVIE_FAILED';